import "antd/es/style/index.css"
import "antd/es/button/style/index.css"
import "antd/es/tooltip/style/index.css"
import "antd/es/input/style/index.css"
import "antd/es/notification/style/index.css"
import "antd/es/message/style/index.css"
import "antd/es/popover/style/index.css"
import "antd/es/alert/style/index.css"
import "antd/es/spin/style/index.css"
import "antd/es/dropdown/style/index.css"
import "antd/es/table/style/index.css"
import "antd/es/upload/style/index.css"
import "antd/es/checkbox/style/index.css"
import "antd/es/radio/style/index.css"
import "antd/es/form/style/index.css"
import "antd/es/input-number/style/index.css"
import "antd/es/modal/style/index.css"
import "antd/es/result/style/index.css"

import "bootstrap/dist/css/bootstrap.min.css"
import "@/styles/style.scss"

import store from "@/redux/provider"
export const wrapRootElement = store
